version: '3.5'
services:

  wildfly1:
    build:
      context: .
      args:
        WILDFLY_NAME: wildfly_1
        CLUSTER_PW: secret_password
    image: wildfly_1
    ports:
    - 8081:8080
    networks:
      - default

  wildfly2:
    build:
      context: .
      args:
        WILDFLY_NAME: wildfly_2
        CLUSTER_PW: secret_password
    image: wildfly_2
    ports:
    - 8082:8080
    networks:
      - default
  
  wildfly3:
    build:
      context: .
      args:
        WILDFLY_NAME: wildfly_3
        CLUSTER_PW: secret_password
    image: wildfly_3
    ports:
    - 8083:8080
    networks:
      - default
  
  wildfly4:
    build:
      context: .
      args:
        WILDFLY_NAME: wildfly_4
        CLUSTER_PW: secret_password
    image: wildfly_4
    ports:
    - 8084:8080
    networks:
      - default