version: "3.7"

services:
    www:
        build: ./dockerfiles/php
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - databases
            - phpmyadmin
            - sftp
        networks:
            - default
    databases:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: 
            --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: examen
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./bd:/docker-entrypoint-initdb.d
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - databases:databases
        ports:
            - 8502:80
        environment:
            PMA_HOST: databases
    sftp:
        image: atmoz/sftp
        volumes:
            - ./www/subdominio:/var/www/html/sftp
        ports:
            - "2222:22"
        command: usuario:123456:2222


